services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gynorg_backend
    restart: always
    networks:
      - gynorg_net
    ports:
      - "6174:8000"
    env_file:
      - .env
    volumes:
      - ./data/uploads:/app/backend/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gynorg_frontend
    restart: always
    networks:
      - gynorg_net
    ports:
      - "7392:80"
    depends_on:
      - backend

networks:
  gynorg_net:
    driver: bridge
