"""Add holiday and school vacation color to calendar settings

Revision ID: 19fb7402e377
Revises: b2c3d4e5f6g7
Create Date: 2026-03-04 14:47:09.337287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '19fb7402e377'
down_revision: Union[str, None] = 'b2c3d4e5f6g7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_settings', sa.Column('holiday_color', sqlmodel.sql.sqltypes.AutoString(), server_default="#EF4444", nullable=False))
    op.add_column('calendar_settings', sa.Column('school_vacation_color', sqlmodel.sql.sqltypes.AutoString(), server_default="#3B82F6", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_settings', 'school_vacation_color')
    op.drop_column('calendar_settings', 'holiday_color')
    # ### end Alembic commands ###
