"""Init Postgres

Revision ID: 9879900c2a64
Revises: 
Create Date: 2026-02-25 14:07:14.536495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9879900c2a64'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('absence_types',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('category', sa.Enum('VACATION', 'SICK_LEAVE', 'TRAINING', 'SPECIAL_LEAVE', 'UNPAID_LEAVE', 'OTHER', name='absencetypecategory'), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('max_days_per_request', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_settings',
    sa.Column('selected_federal_states', sa.JSON(), nullable=True),
    sa.Column('school_holiday_federal_states', sa.JSON(), nullable=True),
    sa.Column('show_nationwide_holidays', sa.Boolean(), nullable=False),
    sa.Column('show_calendar_weeks', sa.Boolean(), nullable=False),
    sa.Column('show_holidays', sa.Boolean(), nullable=False),
    sa.Column('show_school_vacations', sa.Boolean(), nullable=False),
    sa.Column('show_vacation_absences', sa.Boolean(), nullable=False),
    sa.Column('show_sick_leave', sa.Boolean(), nullable=False),
    sa.Column('show_training', sa.Boolean(), nullable=False),
    sa.Column('show_special_leave', sa.Boolean(), nullable=False),
    sa.Column('visible_employee_ids', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('date_hired', sa.Date(), nullable=True),
    sa.Column('federal_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('initials', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=True),
    sa.Column('profile_image_path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('calendar_color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.Column('school_children', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holidays',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('federal_state', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('is_nationwide', sa.Boolean(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('holiday_type', sa.Enum('PUBLIC_HOLIDAY', 'SCHOOL_VACATION', name='holidaytype'), nullable=False),
    sa.Column('federal_state_code', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.Column('school_vacation_type', sa.Enum('WINTER', 'EASTER', 'PENTECOST', 'SUMMER', 'AUTUMN', 'CHRISTMAS', name='schoolvacationtype'), nullable=True),
    sa.Column('data_source', sa.Enum('MANUAL', 'MEHR_SCHULFERIEN_API', 'LEGACY_IMPORT', name='datasource'), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('api_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('absences',
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='absencestatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('absence_type_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['absence_type_id'], ['absence_types.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school_holiday_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('holiday_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.Enum('UPCOMING', 'CONFLICT', 'SUGGESTION', name='notificationtype'), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['holiday_id'], ['holidays.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_holiday_notifications_employee_id'), 'school_holiday_notifications', ['employee_id'], unique=False)
    op.create_index(op.f('ix_school_holiday_notifications_holiday_id'), 'school_holiday_notifications', ['holiday_id'], unique=False)
    op.create_index(op.f('ix_school_holiday_notifications_is_sent'), 'school_holiday_notifications', ['is_sent'], unique=False)
    op.create_index(op.f('ix_school_holiday_notifications_notification_type'), 'school_holiday_notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_school_holiday_notifications_scheduled_date'), 'school_holiday_notifications', ['scheduled_date'], unique=False)
    op.create_table('vacation_allowances',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('annual_allowance', sa.Integer(), nullable=False),
    sa.Column('carryover_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'year', name='unique_employee_year')
    )
    op.create_table('vacation_entitlements',
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacation_entitlements')
    op.drop_table('vacation_allowances')
    op.drop_index(op.f('ix_school_holiday_notifications_scheduled_date'), table_name='school_holiday_notifications')
    op.drop_index(op.f('ix_school_holiday_notifications_notification_type'), table_name='school_holiday_notifications')
    op.drop_index(op.f('ix_school_holiday_notifications_is_sent'), table_name='school_holiday_notifications')
    op.drop_index(op.f('ix_school_holiday_notifications_holiday_id'), table_name='school_holiday_notifications')
    op.drop_index(op.f('ix_school_holiday_notifications_employee_id'), table_name='school_holiday_notifications')
    op.drop_table('school_holiday_notifications')
    op.drop_table('absences')
    op.drop_table('holidays')
    op.drop_table('employees')
    op.drop_table('calendar_settings')
    op.drop_table('absence_types')
    # ### end Alembic commands ###
